version: "3"

services:

  semafor-rest:
    image: msarthur/semafor-rest:latest
    container_name: semafor-rest
    restart: always
    ports:
      - "5000:5000"
    expose:
      - "5000"
    network_mode: "host"
    environment:
      - DOCKER_HOST=192.168.99.100
    deploy:
      resources:
        limits:
          cpus: '128'
          memory: '1G'
    depends_on:
      - db
  semafor-frameparser:
    image: msarthur/semafor-frameparser:latest
    container_name: semafor-frameparser
    network_mode: "host"
    ports:
      - "8085:8085"
    expose:
      - "8085"
    deploy:
      resources:
        limits:
          cpus: '128'
          memory: '4GB'
  db:
    image: mongo
    container_name: semafor-database
    network_mode: "host"
    user: root
    ports:
      - "27017:27017"
    expose:
      - "27017"
