version: "3"

services:

  semafor-rest:
    image: msarthur/semafor-rest:latest
    container_name: semafor-rest
    restart: always
    ports:
      - "5000:5000"
    expose:
      - "5000"
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '128'
          memory: '1G'
  semafor-frameparser:
    image: msarthur/semafor-frameparser:latest
    container_name: semafor-frameparser
    network_mode: "host"
    ports:
      - "8085:8085"
    expose:
      - "8085"
    deploy:
      resources:
        limits:
          cpus: '128'
          memory: '4GB'